name: Build KT-708 Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          swap-storage: false

      - name: Download OpenWrt Image Builder
        run: wget -qO- https://downloads.openwrt.org/releases/24.10.0/targets/ipq40xx/generic/openwrt-imagebuilder-24.10.0-ipq40xx-generic.Linux-x86_64.tar.zst | tar --zstd -xf -

      - name: Inject Passwall2 Repositories
        run: |
          cd openwrt-imagebuilder-*
          echo "src/gz passwall2 https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-24.10/arm_cortex-a7_neon-vfpv4/passwall2" > repositories.conf
          echo "src/gz passwall_packages https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-24.10/arm_cortex-a7_neon-vfpv4/passwall_packages" >> repositories.conf
          echo "src/gz passwall_luci https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-24.10/arm_cortex-a7_neon-vfpv4/passwall_luci" >> repositories.conf

      - name: Build Custom Firmware
        run: |
          cd openwrt-imagebuilder-*
          make image PROFILE="mercury-ti04_708h" PACKAGES="luci luci-i18n-base-en wpad-openssl luci-app-passwall2 luci-i18n-passwall2-en xray-core dnsmasq-full bash coreutils-nohup ip-full dns2socks microsocks" FILES=""

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: KT-708-Firmware
          path: openwrt-imagebuilder-*/bin/targets/ipq40xx/generic/*sysupgrade*.bin
